from enum import Enum

class Characteristics(Enum):
    BRAWN = "Brawn"
    AGILITY = "Agility"
    INTELLECT = "Intellect"
    CUNNING = "Cunning"
    WILLPOWER = "Willpower"
    PRESENCE = "Presence"

class SkillNames(Enum):
    ASTROGATION = "Astrogation"
    ATHLETICS = "Athletics"
    BRAWL = "Brawl"
    CHARM = "Charm"
    COERCION = "Coercion"
    COMPUTERS = "Computers"
    COOL = "Cool"
    COORDINATION = "Coordination"
    CORE_WORLDS = "Core Worlds"
    DECEPTION = "Deception"
    DISCIPLINE = "Discipline"
    EDUCATION = "Education"
    GUNNERY = "Gunnery"
    LEADERSHIP = "Leadership"
    LORE = "Lore"
    MECHANICS = "Mechanics"
    MEDICINE = "Medicine"
    MELEE = "Melee"
    NEGOTIATION = "Negotiation"
    OUTER_RIM = "Outer Rim"
    PERCEPTION = "Perception"
    PILOTING_PLANETARY = "Piloting (Planetary)"
    PILOTING_SPACE = "Piloting (Space)"
    RANGED_HEAVY = "Ranged (Heavy)"
    RANGED_LIGHT = "Ranged (Light)"
    RESILIENCE = "Resilience"
    SKULDUGGERY = "Skulduggery"
    STEALTH = "Stealth"
    STREETWISE = "Streetwise"
    SURVIVAL = "Survival"
    UNDERWORLD = "Underworld"
    VIGILANCE = "Vigilance"
    WARFARE = "Warfare"
    XENOLOGY = "Xenology"
